# !/bin/bash
SCHEMA="org.gnome.desktop.wm.keybindings"
gsettings set $SCHEMA activate-window-menu "@as []"
gsettings set $SCHEMA begin-move "['<Alt>m']"
gsettings set $SCHEMA begin-resize "['<Alt>z']"
gsettings set $SCHEMA close "['<Alt>q']"
gsettings set $SCHEMA cycle-group "@as []"
gsettings set $SCHEMA cycle-group-backward "@as []"
gsettings set $SCHEMA cycle-panels "@as []"
gsettings set $SCHEMA cycle-panels-backward "@as []"
gsettings set $SCHEMA cycle-windows "@as []"
gsettings set $SCHEMA cycle-windows-backward "@as []"
gsettings set $SCHEMA lower "@as []"
gsettings set $SCHEMA maximize "@as []"
gsettings set $SCHEMA minimize "['<Alt>Down']"
gsettings set $SCHEMA move-to-monitor-down "@as []"
gsettings set $SCHEMA move-to-monitor-left "@as []"
gsettings set $SCHEMA move-to-monitor-right "@as []"
gsettings set $SCHEMA move-to-monitor-up "@as []"
gsettings set $SCHEMA move-to-workspace-1 "@as []"
gsettings set $SCHEMA move-to-workspace-2 "@as []"
gsettings set $SCHEMA move-to-workspace-last "@as []"
gsettings set $SCHEMA move-to-workspace-left "@as []"
gsettings set $SCHEMA move-to-workspace-right "@as []"
gsettings set $SCHEMA panel-run-dialog "@as []"
gsettings set $SCHEMA switch-applications "@as []"
gsettings set $SCHEMA switch-applications-backward "@as []"
gsettings set $SCHEMA switch-group "@as []"
gsettings set $SCHEMA switch-group-backward "@as []"
gsettings set $SCHEMA switch-input-source "['<Control>space']"
gsettings set $SCHEMA switch-input-source-backward "['<Shift><Control>space']"
gsettings set $SCHEMA switch-panels "@as []"
gsettings set $SCHEMA switch-panels-backward "@as []"
gsettings set $SCHEMA switch-to-workspace-1 "@as []"
gsettings set $SCHEMA switch-to-workspace-last "@as []"
gsettings set $SCHEMA switch-to-workspace-left "['<Control>Page_Up']"
gsettings set $SCHEMA switch-to-workspace-right "['<Control>Page_Down']"
gsettings set $SCHEMA switch-windows "['<Control>Tab']"
gsettings set $SCHEMA switch-windows-backward "['<Shift><Control>Tab']"
gsettings set $SCHEMA toggle-maximized "['<Alt>Up']"
gsettings set $SCHEMA unmaximize "@as []"
#
SCHEMA="org.gnome.mutter.keybindings"
gsettings set $SCHEMA toggle-tiled-left "['<Alt>Left']"
gsettings set $SCHEMA toggle-tiled-right "['<Alt>Right']"
#
SCHEMA="org.gnome.mutter.wayland.keybindings"
gsettings set $SCHEMA restore-shortcuts "@as []"
#
SCHEMA="org.gnome.settings-daemon.plugins.media-keys"
gsettings set $SCHEMA help "@as []"
gsettings set $SCHEMA logout "@as []"
gsettings set $SCHEMA magnifier "@as []"
gsettings set $SCHEMA magnifier-zoom-in "@as []"
gsettings set $SCHEMA magnifier-zoom-out "@as []"
gsettings set $SCHEMA screenreader "@as []"
gsettings set $SCHEMA screensaver "@as []"
#
SCHEMA="org.gnome.shell.keybindings"
gsettings set $SCHEMA focus-active-notification "@as []"
gsettings set $SCHEMA open-application-menu "@as []"
gsettings set $SCHEMA screenshot "@as []"
gsettings set $SCHEMA screenshot-window "['Print']"
gsettings set $SCHEMA show-screen-recording-ui "@as []"
gsettings set $SCHEMA show-screenshot-ui "['<Control>Print']"
gsettings set $SCHEMA toggle-application-view "@as []"
gsettings set $SCHEMA toggle-message-tray "@as []"
gsettings set $SCHEMA toggle-overview "@as []"
