# !/bin/bash
SCHEMA="org.gnome.desktop.wm.keybindings"
gsettings set $SCHEMA activate-window-menu "@as []"
gsettings set $SCHEMA begin-move "@as []"
gsettings set $SCHEMA begin-resize "@as []"
gsettings set $SCHEMA close "@as []"
gsettings set $SCHEMA cycle-group "@as []"
gsettings set $SCHEMA cycle-group-backward "@as []"
gsettings set $SCHEMA cycle-panels "@as []"
gsettings set $SCHEMA cycle-panels-backward "@as []"
gsettings set $SCHEMA cycle-windows "@as []"
gsettings set $SCHEMA cycle-windows-backward "@as []"
gsettings set $SCHEMA lower "@as []"
gsettings set $SCHEMA maximize "@as []"
gsettings set $SCHEMA minimize "@as []"
gsettings set $SCHEMA move-to-monitor-down "@as []"
gsettings set $SCHEMA move-to-monitor-left "@as []"
gsettings set $SCHEMA move-to-monitor-right "@as []"
gsettings set $SCHEMA move-to-monitor-up "@as []"
gsettings set $SCHEMA move-to-workspace-1 "@as []"
gsettings set $SCHEMA move-to-workspace-2 "@as []"
gsettings set $SCHEMA move-to-workspace-last "@as []"
gsettings set $SCHEMA move-to-workspace-left "@as []"
gsettings set $SCHEMA move-to-workspace-right "@as []"
gsettings set $SCHEMA panel-run-dialog "@as []"
gsettings set $SCHEMA switch-applications "@as []"
gsettings set $SCHEMA switch-applications-backward "@as []"
gsettings set $SCHEMA switch-group "@as []"
gsettings set $SCHEMA switch-group-backward "@as []"
gsettings set $SCHEMA switch-input-source "@as []"
gsettings set $SCHEMA switch-input-source-backward "@as []"
gsettings set $SCHEMA switch-panels "@as []"
gsettings set $SCHEMA switch-panels-backward "@as []"
gsettings set $SCHEMA switch-to-workspace-1 "@as []"
gsettings set $SCHEMA switch-to-workspace-last "@as []"
gsettings set $SCHEMA switch-to-workspace-left "@as []"
gsettings set $SCHEMA switch-to-workspace-right "@as []"
gsettings set $SCHEMA switch-windows "@as []"
gsettings set $SCHEMA switch-windows-backward "@as []"
gsettings set $SCHEMA toggle-maximized "@as []"
gsettings set $SCHEMA unmaximize "@as []"
#
SCHEMA="org.gnome.mutter.keybindings"
gsettings set $SCHEMA toggle-tiled-left "@as []"
gsettings set $SCHEMA toggle-tiled-right "@as []"
#
SCHEMA="org.gnome.mutter.wayland.keybindings"
gsettings set $SCHEMA restore-shortcuts "@as []"
#
SCHEMA="org.gnome.settings-daemon.plugins.media-keys"
gsettings set $SCHEMA help "@as []"
gsettings set $SCHEMA logout "@as []"
gsettings set $SCHEMA magnifier "@as []"
gsettings set $SCHEMA magnifier-zoom-in "@as []"
gsettings set $SCHEMA magnifier-zoom-out "@as []"
gsettings set $SCHEMA screenreader "@as []"
gsettings set $SCHEMA screensaver "@as []"
#
SCHEMA="org.gnome.shell.keybindings"
gsettings set $SCHEMA focus-active-notification "@as []"
gsettings set $SCHEMA open-application-menu "@as []"
gsettings set $SCHEMA screenshot "@as []"
gsettings set $SCHEMA screenshot-window "@as []"
gsettings set $SCHEMA show-screen-recording-ui "@as []"
gsettings set $SCHEMA show-screenshot-ui "@as []"
gsettings set $SCHEMA toggle-application-view "@as []"
gsettings set $SCHEMA toggle-message-tray "@as []"
gsettings set $SCHEMA toggle-overview "@as []"
