# !/bin/bash
SCHEMA="org.gnome.Terminal.Legacy.Keybindings"
FOLDER="/org/gnome/terminal/legacy/keybindings/"
gsettings set $SCHEMA:$FOLDER close-tab 'disabled'
gsettings set $SCHEMA:$FOLDER close-window 'disabled'
gsettings set $SCHEMA:$FOLDER copy 'disabled'
gsettings set $SCHEMA:$FOLDER detach-tab 'disabled'
gsettings set $SCHEMA:$FOLDER find 'disabled'
gsettings set $SCHEMA:$FOLDER find-clear 'disabled'
gsettings set $SCHEMA:$FOLDER find-next 'disabled'
gsettings set $SCHEMA:$FOLDER find-previous 'disabled'
gsettings set $SCHEMA:$FOLDER full-screen 'disabled'
gsettings set $SCHEMA:$FOLDER move-tab-left 'disabled'
gsettings set $SCHEMA:$FOLDER move-tab-right 'disabled'
gsettings set $SCHEMA:$FOLDER new-tab 'disabled'
gsettings set $SCHEMA:$FOLDER new-window 'disabled'
gsettings set $SCHEMA:$FOLDER next-tab 'disabled'
gsettings set $SCHEMA:$FOLDER paste 'disabled'
gsettings set $SCHEMA:$FOLDER prev-tab 'disabled'
gsettings set $SCHEMA:$FOLDER read-only 'disabled'
gsettings set $SCHEMA:$FOLDER reset 'disabled'
gsettings set $SCHEMA:$FOLDER reset-and-clear 'disabled'
gsettings set $SCHEMA:$FOLDER switch-to-tab-1 'disabled'
gsettings set $SCHEMA:$FOLDER switch-to-tab-2 'disabled'
gsettings set $SCHEMA:$FOLDER switch-to-tab-3 'disabled'
gsettings set $SCHEMA:$FOLDER switch-to-tab-4 'disabled'
gsettings set $SCHEMA:$FOLDER switch-to-tab-5 'disabled'
gsettings set $SCHEMA:$FOLDER switch-to-tab-6 'disabled'
gsettings set $SCHEMA:$FOLDER switch-to-tab-7 'disabled'
gsettings set $SCHEMA:$FOLDER switch-to-tab-8 'disabled'
gsettings set $SCHEMA:$FOLDER switch-to-tab-9 'disabled'
gsettings set $SCHEMA:$FOLDER switch-to-tab-10 'disabled'
gsettings set $SCHEMA:$FOLDER zoom-in 'disabled'
gsettings set $SCHEMA:$FOLDER zoom-normal 'disabled'
gsettings set $SCHEMA:$FOLDER zoom-out 'disabled'